export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_SORT_BY_LIST ="GET_SORT_BY_LIST";
export const GET_CATEGORY_LIST ="GET_CATEGORY_LIST";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const DELETE_PRODUCT_BY_ID = "DELETE_PRODUCT_BY_ID";
export const EDIT_PRODUCT_BY_ID = " EDIT_PRODUCT_BY_ID ";
