export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const DELETE_PRODUCT = "DELETE_PRODUCT_BY_ID";
export const EDIT_PRODUCT = " EDIT_PRODUCT_BY_ID ";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
